### PR TITLE
Fix CT flow with custom queries bugs.

### LINKED ISSUE #20: [BUG] Broken ctMinValidVersion check if ct_changes_query is passed
### Describe the problem

If `ct_changes_query` argument is passed, `CustomChangeTrackingHandler` is used and check `changeTrackingLastVersion >= ctMinValidVersion` doesn't performed because it is located in `query` of `ChangeTrackingHandler`.

#### Steps to reproduce

Config example:
```yaml
  arguments:
    - "change_tracking==true"
    - "primary_key==Id,FilId"
    - "schema==dbo"
    - "tab==VS_ct_test4"
    - "path_to_save==s3a://warehouse/anotherdb.db/"
    - "hive_db==anotherdb"
    - "ct_current_version_query==exec dbo.getCTCurrentVersion"
    - "ct_min_valid_version_query==exec dbo.getCTMinValidVersionQuery ?"
    - "ct_min_valid_version_params==defaultSQLTable"
    - "ct_changes_query==exec dbo.getCTChanges_VS_ct_test4 ?, ?, ?"
    - "ct_changes_query_params==defaultSQLTable, queryCTLastVersion, queryCTCurrentVersion"
```

#### Observed results

Check `changeTrackingLastVersion >= ctMinValidVersion` is not execured.

#### Expected results

Check `changeTrackingLastVersion >= ctMinValidVersion` has to be execured.

### Environment information

* Mirroring library version: 1.0.3
* Spark version: 3.2.3
* Scala version: 2.13.5

### Willingness to contribute

The Delta Flow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Flow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Flow community.
- [ ] No. I cannot contribute a bug fix at this time.

### PR DESCRIPTION
**Pull request by VShkaberda**
Fixes #20 and #22

### CODE REVIEW

File: src/main/scala/mirroring/Runner.scala [hunk 1]
```diff
@@ -51,30 +51,29 @@ object Runner extends LogSupport {
...
 
-    var jdbcService: JdbcService = new JdbcService(jdbcContext)
-
-    if (config.splitBy.nonEmpty) {
-      jdbcService = new JdbcPartitionedService(jdbcContext)
-    }
-
-    if (config.isChangeTrackingEnabled && config.CTChangesQuery.nonEmpty) {
-      jdbcService = new JdbcCTService(jdbcContext)
+    val jdbcDF: DataFrame = if (config.CTChangesQuery.isEmpty) {
```
Comment (hanna-liashchuk) [inline src/main/scala/mirroring/Runner.scala:64]: in this case, normal CT won't ever work, is that so?

Comment (VShkaberda) [reply src/main/scala/mirroring/Runner.scala:64]: If `config.CTChangesQuery.isEmpty` then `JdbcService(jdbcContext)` is instantiated and `changeTrackingHandler.query` is passed to its method `loadData`. If that's what you mean. Works fine.

**Review by hanna-liashchuk — APPROVED** [review]
